[build]
  command = "npm --prefix client install && npm --prefix server install && npm --prefix client run build"
  publish = "client/dist"
  functions = "server/netlify/functions"

[functions]
  included_files = ["server/db/**"]
  external_node_modules = ["pg", "pg-hstore", "sequelize"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200