[build]
  command = "npm --prefix client ci && npm --prefix server ci && npm --prefix client run build"
  publish = "client/dist"
  functions = "server/netlify/functions"

[functions]
  included_files = ["server/db/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
